apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hd473t7gj-go 
  janus-idp.io/tekton: hd473t7gj-go
  backstage.io/kubernetes-id: hd473t7gj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hd473t7gj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  