apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hd473t7gj-go-gitops
  description: This is GitOps manifest for hd473t7gj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: hd473t7gj-go
    backstage.io/kubernetes-id: hd473t7gj-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hd473t7gj-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hd473t7gj-go
